### ISSUE TITLE
!DOCTYPE blocking access to the rest of the document?

### ISSUE THREAD

**Issue by benspratling4** [samchon/sxml#2]
This was easy to install, and pretty easy to start using.
The format I need to parse sometimes has a "!DOCTYPE" tag, and I don't know how to get my real element from the XML.

**Comment by samchon** [comment]
Can you show me an example? For a temporary, cut the vulnerable string by yourself. I'll patch it later.

**Comment by benspratling4** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.0">
</score-partwise>

**Comment by benspratling4** [comment]
For brevity, I'm leaving out everything that goes in the "score-partwise" node.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.0"></score-partwise>`

**Comment by benspratling4** [comment]
I've tried posting a sample of the XML in question multiple times, and GitHub seems to be unable to display it.  Here's a reference to a description of using both the "?xml" and "!DOCTYPE" tags. https://en.wikipedia.org/wiki/Document_type_definition

**Comment by samchon** [comment]
Thanks for your reference. This is Simple XML library not supporting full spec of XML standard. 

May I ignore and erase the `!DOCTYPE` element?

**Comment by benspratling4** [comment]
For what I'm using it for, yes.  For my local sources, I've just copied the pasted the code that deleted the comments.
`//ERASE COMMENTS
		while ((start = str.indexOf("", start);
			if (end == -1)
				break;

			str = str.substr(0, start) + str.substr(end + 3);
		}
		//ERASE DOCTYPE
		while ((start = str.indexOf("<!DOCTYPE")) != -1) 
		{
			end = str.indexOf(">", start);
			if (end == -1)
				break;

			str = str.substr(0, start) + str.substr(end + 1);
		}
`

**Comment by samchon** [comment]
The new patch `v0.0.9` has published. It ignores and erases the `<!DOCTYPE>` element.

Below code works well.

```typescript
const lib = require("./lib/index");

let str = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE people_list [
  <!ELEMENT people_list (person*)>
  <!ELEMENT person (name, birthdate?, gender?, socialsecuritynumber?)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT birthdate (#PCDATA)>
  <!ELEMENT gender (#PCDATA)>
  <!ELEMENT socialsecuritynumber (#PCDATA)>
]>
<people_list>
  <person>
    <name>Fred Bloggs</name>
    <birthdate>2008-11-27</birthdate>
    <gender>Male</gender>
  </person>
</people_list>`;

let xml = new lib.XML(str);
console.log(xml.toString());
```

**Comment by benspratling4** [comment]
Thanks.  Unfortunately, I just realized after reading through your code, that you're storing child nodes by collecting them into independent lists based on tag, which effectively erases the ordering of the elements with different tags in the original file.  Since the file format I'm parsing relies on the relative order of child elements with different tags to communicate important information, I won't be able to use your package after all.
